spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: ${LOCAL_DB_URL}
    username: ${LOCAL_DB_USER}
    password: ${LOCAL_DB_PASSWORD}

  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
  jpa:
    open-in-view: true
    hibernate:
      ddl-auto: update
    show-sql: true
  properties:
    hibernate.format_sql: true
    dialect: org.hibernate.dialect.MySQL8InnoDBDialect

  main:
    allow-bean-definition-overriding: true

  redis:
    host: ${REDIS_HOST}
    port: ${REDIS_PORT}



cloud:
  aws:
    s3:
      bucket: ${AWS_S3_NAME}
    stack.auto: false
    region.static: ${AWS_REGION}
    credentials:
      accessKey: ${AWS_S3_ACCESS_KEY}
      secretKey: ${AWS_S3_SECRET_KEY}